from __future__ import annotations

from typing import AsyncIterator, Protocol


class BaseLLMClient(Protocol):
    async def complete(self, prompt: str, **kwargs) -> str: ...
    async def stream(self, prompt: str, **kwargs) -> AsyncIterator[str]: ...
    async def complete_with_messages(self, messages: list[dict], **kwargs) -> str: ...
